server:
  port: 8081

quant:
  langchain:
    api: ${LANGCHAIN_API:http://langchain-agent:8083}

spring:
  application:
    name: quant-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://quant_keycloak:8080/realms/quant/protocol/openid-connect/certs"

  datasource:
    url: jdbc:mysql://192.168.1.26:13306/workflow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@mongodb:27017/quantdb?authSource=admin}
      database: quantdb
